### ISSUE TITLE
Link to SUBMISSION-GUIDELINES.md not working

### ISSUE THREAD

**Issue by pietroblandizzi** [Joystream/founding-members#10]
The link to the file is broken. The path  should be fixed

`https://github.com/Joystream/founding-members/blob/main/SUBMISSION-GUIDANCE.md`

`https://github.com/Joystream/founding-members/blob/main/SUBMISSION-GUIDELINES.md`

**Comment by blrhc** [comment]
Fixed here: https://github.com/Joystream/founding-members/pull/11
Thank you very much for pointing it out :)
